/*
 * This source file was generated by the Gradle 'init' task
 */
package triviaucab.tui;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        TriviaUCAB.AppTabletop classUnderTest = new TriviaUCAB.AppTabletop();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
